### ISSUE TITLE
Rendre le rouge au-dessus du reste

### ISSUE THREAD

**Issue by JBosm** [osm-fr/bano-cartocss#1]
C'est vrai que faire apparaitre beaucoup de vert et de jaune, c'est vachement plus « comm' », par contre, aux niveaux de zoom intermédiaires, ça rend plus difficile le repérage du rouge, c'est-à-dire là où il faudrait aller se balader. Je verrais bien le rouge (cadastre non rapproché) au-dessus des autres couleurs. 
PS : J'ai pas vérifié pour le mauve…

**Comment by cquest** [comment]
C'est (enfin) le cas ;)
